### PR TITLE
EBODAC-511 - fixed issue with GetVisitsDataFromRaveuiTest (19-08-2106)

### PR DESCRIPTION
**Pull request by rubenmartin**
Fixes for the new case GetVisitsDataFromRaveuiTest

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by rubenmartin** [comment]
@pmuchowski  please tests this new PR

**Comment by pmuchowski** [comment]
test this please

**Comment by rubenmartin** [comment]
Thank you @pmuchowski

**Pull request merged**
