### PR TITLE
EBODAC-913 - QA - Fix checkstyle issues in automatic QA/UI and Integr…

### PR DESCRIPTION
**Pull request by MikolajBasSoldevelo**
…ation/Unit Tests

### CODE REVIEW

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test his please

**Comment by pmuchowski** [comment]
test this please

**Comment by pmuchowski** [comment]
test this please

**Comment by pmuchowski** [comment]
test this please

**Comment by pmuchowski** [comment]
test this please

**Pull request merged**
