### PR TITLE
EBODAC-531 QA - Users - Admin Have access only to EBODAC Test

### PR DESCRIPTION
**Pull request by nataliaplonka**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Pull request merged**
