### PR TITLE
EBODAC-645: Added base for the Booking App module

### PR DESCRIPTION
**Pull request by ngraczewski**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by ngraczewski** [comment]
test this please

**Comment by ngraczewski** [comment]
test this please

**Comment by ngraczewski** [comment]
test this please

**Comment by ngraczewski** [comment]
test this please

**Comment by ngraczewski** [comment]
test this please

**Comment by ngraczewski** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Pull request closed without merging**
