### PR TITLE
EBODAC-509 "QA Zetes Import Data - Get Participant from Zetes Test"

### PR DESCRIPTION
**Pull request by tomaszmueller**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by pmuchowski** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by tomaszmueller** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Pull request closed without merging**
