### PR TITLE
EBODAC-800 Selenium test

### PR DESCRIPTION
**Pull request by PiotrZurawskiSolDevelo**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by PiotrZurawskiSolDevelo** [comment]
test this please

**Comment by PiotrZurawskiSolDevelo** [comment]
test this please

**Comment by PiotrZurawskiSolDevelo** [comment]
@kkaczmarczyk @pmuchowski can I ask for merge?

**Pull request merged**
