### PR TITLE
EBODAC-511 - Adding amends for GenerateParticipantAndVisitsUiTests (09-09-2016)

### PR DESCRIPTION
**Pull request by rubenmartin**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by rubenmartin** [comment]
@pmuchowski  please test these fixes

**Comment by pmuchowski** [comment]
test this please

**Comment by rubenmartin** [comment]
@pmuchowski  thanks

**Pull request merged**
