### PR TITLE
EBODAC-801 "QA - Booking Application - (Screen 4) - Reschedule a visi…

### PR DESCRIPTION
**Pull request by tomaszmueller**
…t Test"

### CODE REVIEW

**Comment by tomaszmueller** [comment]
@aczyrko things left to do in this test:
Improve setting date so that appropriate month will be chosen and date set will be current date+5days(as written in Test Case)
improve clicking on sorting planned date, currently it's only clicking when browser is in full-screen mode

**Comment by tomaszmueller** [comment]
@aczyrko I added expanding browser to full-screen, which fixed clicking on sorting planned date, but the date cannot be set on current date+5days because this date may be disabled on application.
It needs to be discussed and decided which date to put in this test.

**Comment by tomaszmueller** [comment]
@aczyrko, @kkaczmarczyk should be OK now

**Comment by tomaszmueller** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
@tomaszmueller  Cool. I see 4 commits in this PR - could you squash them? 
I will run the UI test on CI, once they are

**Comment by tomaszmueller** [comment]
@kkaczmarczyk as the commits were being done during long period of time, it is risky to squash them now as it may cause additional conflicts

**Comment by kkaczmarczyk** [comment]
@tomaszmueller squashing commits won't add any conflicts, it should just merge all of the commits into one. you can refer to http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by tomaszmueller** [comment]
moved this PR to https://github.com/motech-implementations/ebodac/pull/581
this one can be closed

**Pull request closed without merging**
