### PR TITLE
EBODAC-511 - Fix on the last issues detected (14-09-2016)

### PR DESCRIPTION
**Pull request by rubenmartin**
@pmuchowski  please add for Unit Tests

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by pmuchowski** [comment]
test this please

**Comment by pmuchowski** [comment]
test this please

**Comment by rubenmartin** [comment]
@pmuchowski  could you re-run the tests , for the other pr it worked, I do not have access to force this one merge

**Comment by pgesek** [comment]
test this please

**Comment by rubenmartin** [comment]
@pmuchowski  it was success , please could you merge ?

**Pull request merged**
