### PR TITLE
EBODAC-445 Meaningfull filename should be suggested when exporting re…

### PR DESCRIPTION
**Pull request by MikolajBasSoldevelo**
…cords instead of entity

### CODE REVIEW

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by pmuchowski** [comment]
test this please

**Pull request merged**
