### PR TITLE
EBODAC-811 Selenium Test

### PR DESCRIPTION
**Pull request by PiotrZurawskiSolDevelo**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by aczyrko** [comment]
test this please

**Comment by PiotrZurawskiSolDevelo** [comment]
@pmuchowski @kkaczmarczyk  can I ask for run tests?

**Comment by PiotrZurawskiSolDevelo** [comment]
test this please

**Comment by PiotrZurawskiSolDevelo** [comment]
test this please

**Pull request merged**
