### PR TITLE
EBODAC-188 DEV TASK - Subject Registration - Add fields district/ chi…

### PR DESCRIPTION
**Pull request by MikolajBasSoldevelo**
…efdom / section

### CODE REVIEW

**Comment by motech-github** [comment]
Can one of the admins verify this patch?

**Comment by koshalt** [comment]
ok to test

**Comment by koshalt** [comment]
test this please

**Comment by koshalt** [comment]
ok to test

**Comment by koshalt** [comment]
test this please

**Comment by koshalt** [comment]
ok to test

**Comment by koshalt** [comment]
test this please

**Comment by koshalt** [comment]
ok to test

**Comment by koshalt** [comment]
test this please

**Comment by koshalt** [comment]
ok to test

**Comment by koshalt** [comment]
test this please

**Comment by koshalt** [comment]
ok to test

**Comment by kkaczmarczyk** [comment]
ok to test

**Comment by kkaczmarczyk** [comment]
test this please

**Pull request merged**
