### PR TITLE
EBODAC-861: DEV - TASK - Stage II Changes - Prime Vaccination First F…

### PR DESCRIPTION
**Pull request by pmuchowski**
…ollow up - change on stage 1

### CODE REVIEW

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by pmuchowski** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by pmuchowski** [comment]
test this please

**Pull request merged**
