### PR TITLE
EBODAC-527 "QA - Analyst cannot modify an field on the participants"

### PR DESCRIPTION
**Pull request by tomaszmueller**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by pmuchowski** [comment]
test this please

**Comment by tomaszmueller** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by tomaszmueller** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
@tomaszmueller please resolve conflicts with master branch. Thanks in advance

**Comment by kkaczmarczyk** [comment]
closing until conflicts will be resolved

**Pull request closed without merging**
