### PR TITLE
EBODAC-934 Selenium Test

### PR DESCRIPTION
**Pull request by PiotrZurawskiSolDevelo**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by PiotrZurawskiSolDevelo** [comment]
test this please

**Comment by PiotrZurawskiSolDevelo** [comment]
@pmuchowski can You run tests for this PR?

**Comment by pmuchowski** [comment]
test this please

**Comment by PiotrZurawskiSolDevelo** [comment]
@pmuchowski  can You merge it?

**Pull request merged**
