### PR TITLE
EBODAC-913 checkstyle fix in Selenium tests.

### PR DESCRIPTION
**Pull request by PiotrZurawskiSolDevelo**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
@PiotrZurawskiSolDevelo there are compilation errors happening. Refer to: 
http://ci.motechproject.org/job/EBODAC/1104/console
Build can't pass with these

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by PiotrZurawskiSolDevelo** [comment]
@kkaczmarczyk I resolve problem with this error.

**Pull request merged**
