### PR TITLE
EBODAC-511 - Fixing for last issues appeared on staging (24-08-2016)

### PR DESCRIPTION
**Pull request by rubenmartin**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by rubenmartin** [comment]
@pmuchowski  please test this change

**Comment by pmuchowski** [comment]
test this please

**Comment by pmuchowski** [comment]
test this please

**Comment by rubenmartin** [comment]
Thanks @pmuchowski

**Pull request merged**
