### PR TITLE
Fixed problem with ui-remote

### PR DESCRIPTION
**Pull request by tomaszmueller**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
@tomaszmueller  please resolve the conflict

**Comment by tomaszmueller** [comment]
@kkaczmarczyk please close this PR and go to https://github.com/motech-implementations/ebodac/pull/235
this PR is from fork so should have no further problems with merging commis and fixing conflicts

**Pull request closed without merging**
