### PR TITLE
EBODAC-511 - Added new fixes with the last issues. Added few delays and better Screen creation (29-08-2016)

### PR DESCRIPTION
**Pull request by rubenmartin**
In order to avoid the last issue in Jenkins and the tests I have added more delays and for the Generation of Participant and Visits more control.

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by rubenmartin** [comment]
@pmuchowski  please test

**Comment by pmuchowski** [comment]
test this please

**Comment by rubenmartin** [comment]
@pmuchowski  thanks

**Comment by rubenmartin** [comment]
Thanks @pmuchowski

**Pull request merged**
