### PR TITLE
EBODAC-511 - Fixing last issues with ui test (25-08-2016)

### PR DESCRIPTION
**Pull request by rubenmartin**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by rubenmartin** [comment]
@pmuchowski  please test

**Comment by pmuchowski** [comment]
test this please

**Comment by rubenmartin** [comment]
@pmuchowski  please merge it look like is all fine.

**Comment by rubenmartin** [comment]
@pmuchowski thanks a lot :)

**Pull request merged**
