### PR TITLE
EBODAC-529: "QA - Analyst clicks on any row stays on the same screen …

### PR DESCRIPTION
**Pull request by tomaszmueller**
…Test"

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by tomaszmueller** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
@tomaszmueller please resolve conflicts with master branch. Thanks in advance

**Comment by kkaczmarczyk** [comment]
closing until conflicts will be resolved

**Pull request closed without merging**
