### PR TITLE
Added Change Phone Number Test for EBODAC-508

### PR DESCRIPTION
**Pull request by tomaszmueller**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by pgesek** [comment]
test this please

**Comment by pgesek** [comment]
test this please

**Comment by pgesek** [comment]
test this please

**Comment by pgesek** [comment]
@tomaszmueller @kkaczmarczyk I installed Chromedriver on the CI. I've also set an environment variable for the Ebodac build - DISPLAY=:99.0 , which is required since we have Xvfb running on screen 99. Anyway it seems to be working, but the tests are timining out, which might be related to Motech not starting, but the Chromedriver starts succesfully, so I am assuming thats on your end. Let me know if there any issues.

**Comment by tomaszmueller** [comment]
@pgesek Can it be related to this problem: https://applab.atlassian.net/browse/EBODAC-523 ?

**Comment by pgesek** [comment]
@tomaszmueller Unlikely, it seems to not even reach the login screen.

**Comment by kkaczmarczyk** [comment]
@pgesek thanks a lot for setting chromedriver with mr Jenkins

**Comment by kkaczmarczyk** [comment]
test this pls

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this pls

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Pull request closed without merging**
