### PR TITLE
EBODAC-504 added user helpers to ebodac

### PR DESCRIPTION
**Pull request by tomaszmueller**
Added Helpers to use other users in UI Tests in Ebodac

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by pmuchowski** [comment]
test this please

**Pull request merged**
