### PR TITLE
EBODAC-508 fixed problem on ui-remote nad changed pom to run ui-remot…

### PR DESCRIPTION
**Pull request by tomaszmueller**
…e from browser

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by kkaczmarczyk** [comment]
ui-remote profile was already fixed in https://github.com/motech-implementations/ebodac/commit/173f92be70b6e5a5ddca3a7cbef827b012458e5f

please rebase this PR - it has conflicts

**Comment by tomaszmueller** [comment]
rebased

**Comment by kkaczmarczyk** [comment]
remove also Created by tomasz information everywhere
it could be good to disable such setting in your IDE

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
make a rebase of your only commit

**Comment by kkaczmarczyk** [comment]
@tomaszmueller  you have more than 10 commits in this PR, please resolve it

**Comment by tomaszmueller** [comment]
please close this PR
fix for this issue is in https://github.com/motech-implementations/ebodac/pull/231

**Pull request closed without merging**
