### PR TITLE
EBODAC-1079 - Fixed issue with the JS error for the date-picker (05-08-2016)

### PR DESCRIPTION
**Pull request by rubenmartin**
fix issue with ebodac report

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by rubenmartin** [comment]
@pmuchowski  please test this PR

**Comment by pmuchowski** [comment]
test this please

**Comment by rubenmartin** [comment]
@pmuchowski  tests passed, I think we can merge this ticket

**Pull request merged**
