### PR TITLE
EBODAC-637 - DEV - Fix needs braces checkstyle errors

### PR DESCRIPTION
**Pull request by MikolajBasSoldevelo**

### CODE REVIEW

**Comment by MikolajBasSoldevelo** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
name of the pr is not right EBODAC-367  -> EBODAC-637

**Comment by MikolajBasSoldevelo** [comment]
test this please

**Pull request merged**
