### PR TITLE
EBODAC-805 "QA - Reports - Daily Clinic Visit Schedule Report"

### PR DESCRIPTION
**Pull request by tomaszmueller**

### CODE REVIEW

**Comment by tomaszmueller** [comment]
test this please

**Comment by tomaszmueller** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
@tomaszmueller please resolve conflicts. Thanks in advance

**Comment by tomaszmueller** [comment]
@kkaczmarczyk resolved

**Comment by tomaszmueller** [comment]
test this please

**Pull request merged**
