### PR TITLE
EBODAC-511 - Changes to fix the issues detected with Analist/Admin te…

### PR DESCRIPTION
**Pull request by rubenmartin**
…sting and improment on clean code for other tests (27-07-2016)

### CODE REVIEW

**Comment by rubenmartin** [comment]
@pmuchowski  could you add this PR for Integration Tests ?. Then please merge it.

**Comment by pmuchowski** [comment]
test this please

**Comment by pmuchowski** [comment]
@rubenmartin I looked into the code and you are using e.printStackTrace(), but it's better just to add the stacktrace to the logger: log.error("some message", e);
The name of the test class needs to end with "UiTest", you should rename AdminAccessToEbodacTabsTest.java

**Comment by rubenmartin** [comment]
@pmuchowski  I have added the same approach in every class where it was added in Ebodac (main / test) the printstacktrace, now we have 1 strategy. Added some fixing to have more stability in the last uiTest added, please test them.

**Comment by rubenmartin** [comment]
@pmuchowski  thanks for your input and new commit pushed (https://github.com/motech-implementations/ebodac/commit/52045796c6b7d6f380383dda560ab675b1457118)

**Comment by pmuchowski** [comment]
test this please

**Comment by pmuchowski** [comment]
test this please

**Comment by rubenmartin** [comment]
@pmuchowski  thanks !

**Pull request merged**
