### PR TITLE
EBODAC-512 "QA - Get Visit Data from RAVE Test"

### PR DESCRIPTION
**Pull request by tomaszmueller**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by pmuchowski** [comment]
test this please

**Comment by pmuchowski** [comment]
test this please

**Comment by tomaszmueller** [comment]
test this please

**Comment by tomaszmueller** [comment]
test this please

**Comment by kkaczmarczyk** [comment]
@tomaszmueller please resolve conflicts with master branch. Thanks in advance

**Comment by tomaszmueller** [comment]
test this please

**Comment by tomaszmueller** [comment]
@kkaczmarczyk conflicts resolved and test fixed

**Pull request merged**
